### PR TITLE
[Ready to Publish] Spanish Planning and Policies Overview

### PR DESCRIPTION
**Pull request by cmuncharaz**
Translation of the "Planning and Policies Overview" document into Spanish.

### CODE REVIEW

**Comment by yatil** [comment]
@yatil (that’s me!) rename `last_update` in the front matter to `last_updated`. ([The D was obviously silent.](https://www.youtube.com/watch?v=ci4g8D5wSww))

**Comment by slhenry** [comment]
> @yatil (that’s me!) rename last_update in the front matter to last_updated. (The D was obviously silent.)

done. :-)

**Comment by yatil** [comment]
@slhenry I had to do it in the English version as well: https://github.com/w3c/wai-plan-policies-overview/pull/2/commits/846158429d5eedd595f3ecde32cfefd3091869b3 I just learned that I can edit @cmuncharaz’ master branch. What sorcery is this? (Not that I complain! 😃)

**Comment by slhenry** [comment]
> @slhenry I had to do it in the English version as well

yup did there, too :-)

https://github.com/w3c/wai-plan-policies-overview/commit/62376985a591c56e37c52471edec7073dd0ffe75#diff-d680e8a854a7cbad6d490c445cba2eba

**Pull request merged**
